# -*- coding: utf-8 -*-
"""Group Assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cH9ZVS9jkJTo-1w-udFTy4LUPSL9m3gz

Car dealer – 
The idea is to create a database for all cars sold by a used car dealership in State College. 
We are trying to analyze the used car business, such as understanding the features that customers are interested in and what cars are easier to sell. 
Our idea will expand to understand the buyer’s purchasing decision behavior, so the business becomes more profitable and efficient. 
The database can be analyzed for marketing purposes; for example, advertisements can be direct to the targeted demographic. 
Also, the data can be sold to cars manufacturers’, so they can develop more profitable models in the future. 
Car sales data are collected by the manufacturer mostly for new cars since they do not benefit from the sale of used cars, and this type of data is hardly shared. 
What makes our data unique that it is collected at a micro-level by the car dealer instead of the manufacture. 
Detailed data is an advantage because it provides connections between different trends such as how many times the customer visited the dealership before making the final purchase. 
All of our data will be collected from an existing used car dealership in State College. 
Car dealerships usually open from 9 am to 7 or 9 pm, and customer walk shopping for cars available. S
ome customer shop for cars online before coming to the dealer to inspect the car. 
Once the customer selects a car, the salesman will explain the financing options to finalize the deal by signing paperwork. 
Data should be collected from the beginning once the customer walks to the dealer or browse the website. 
We can record the screening time on certain models, and what model’s customer spend more time researching. Ordinary data, such as the count of cars sold, make, model and color can be easily collected at the final step of the purchase. Also, information from old paperwork can be entered manually into the database, so we can have more accurate data. Customers can be asked to fill a survey after the final sale is done in exchange for a small discount or any kind of incentive. A survey are a good option for any data that is hard to be collected without the customer answering lengthy questions. For example, did the customer visited different car dealers? Or what are the most attractive features in the car?. Some of the data should be filled after the sale is done by the salesmen regarding information like how many times the customer visited the dealership. It is also important to work on making the data recording process automated without any employee as much as possible because it is time-consuming. 
Database design is a complex step, but it is a necessary process. 
it is important to store the data in one place, so all employees from the different department can have access. 
This allows employees to apply available information in improving their department.  
After collecting, analyzing, and understanding the data, the dealer should use the data to make the business more efficient and successful. 
All in all, the data will give a better understanding of the used car dealership business.
"""
